- platform: mqtt
  name: "Kitchen Main"
  state_topic: "home/status/main/2320"
  command_topic: "home/main/2320"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Lighting"
  state_topic: "home/status/main/2321"
  command_topic: "home/main/2321"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light"
  state_topic: "home/status/main/2322"
  command_topic: "home/main/2322"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light Left"
  state_topic: "home/status/main/2323"
  command_topic: "home/main/2323"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light Right"
  state_topic: "home/status/main/2324"
  command_topic: "home/main/2324"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Venting"  
  state_topic: "home/status/main/2325"
  command_topic: "home/main/2325"
  payload_on: "ON"
  payload_off: "OFF"     
  state_on: "ON"       
  state_off: "OFF"       

- platform: mqtt
  name: "Kitchen Fan"
  state_topic: "home/status/main/2326"
  command_topic: "home/main/2326"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Warm Floor"
  state_topic: "home/status/main/2327"
  command_topic: "home/main/2327"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
