- platform: mqtt
  name: "Kitchen Main"
  state_topic: "home/status/main/1320"
  command_topic: "home/main/1320"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Lighting"
  state_topic: "home/status/main/1321"
  command_topic: "home/main/1321"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light"
  state_topic: "home/status/main/1322"
  command_topic: "home/main/1322"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light Left"
  state_topic: "home/status/main/1323"
  command_topic: "home/main/1323"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Guest Zone Light Right"
  state_topic: "home/status/main/1324"
  command_topic: "home/main/1324"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Venting"  
  state_topic: "home/status/main/1325"
  command_topic: "home/main/1325"
  payload_on: "ON"
  payload_off: "OFF"     
  state_on: "ON"       
  state_off: "OFF"       

- platform: mqtt
  name: "Kitchen Fan"
  state_topic: "home/status/main/1326"
  command_topic: "home/main/1326"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "Kitchen Warm Floor"
  state_topic: "home/status/main/1327"
  command_topic: "home/main/1327"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"
