- platform: mqtt
  name: "1560"
  state_topic: "home/status/main/1560"
  command_topic: "home/main/1560"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1561"
  state_topic: "home/status/main/1561"
  command_topic: "home/main/1561"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1562"
  state_topic: "home/status/main/1562"
  command_topic: "home/main/1562"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1313"
  state_topic: "home/status/main/1313"
  command_topic: "home/main/1563"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1564"
  state_topic: "home/status/main/1564"
  command_topic: "home/main/1564"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1565"  
  state_topic: "home/status/main/1565"
  command_topic: "home/main/1565"
  payload_on: "ON"
  payload_off: "OFF"     
  state_on: "ON"       
  state_off: "OFF"       

- platform: mqtt
  name: "1566"
  state_topic: "home/status/main/1566"
  command_topic: "home/main/1566"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

- platform: mqtt
  name: "1567"
  state_topic: "home/status/main/1567"
  command_topic: "home/main/1567"
  payload_on: "ON"
  payload_off: "OFF"
  state_on: "ON"
  state_off: "OFF"

