# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
mqtt: !include switches.yaml

homeassistant:
  packages: !include_dir_named packages

sensor:
  - platform: integration
    source: sensor.deye_5kw_power_losses
    name: deye_5kw_energy_losses
    unit_prefix: k
    method: trapezoidal

utility_meter:
  deye_5_losses_daily:
    source: sensor.deye_5kw_energy_losses
    cycle: daily

input_boolean:
  my_flag1:
    name: Air conditioning cooling
    icon: mdi:toggle-switch
  my_flag2:
    name: Air conditioning heating
    icon: mdi:toggle-switch
  my_flag3:
    name: Boiler night charge
    icon: mdi:toggle-switch
  my_flag4:
    name: Heating enabled
    icon: mdi:toggle-switch

input_datetime:
  selling_start_time:
    name: Selling Start Time
    has_date: false
    has_time: true

  selling_stop_time:
    name: Selling Stop Time
    has_date: false
    has_time: true

shell_command:
  bizon_suspend: echo vfnhjc | ssh -tt yurii@192.168.150.4 'sudo -S systemctl suspend -i'
  bizon_reboot: echo vfnhjc | ssh -tt yurii@192.168.150.4 'sudo reboot'

