# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
mqtt: !include switches.yaml

homeassistant:
  packages: !include_dir_named packages

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.16.0.0/12
    - 192.168.1.0/24
    - 192.168.1.1       # Внутрішня IP-адреса вашого роутера OpenWrt
    - fe80::/10

template:
  - sensor:
      - name: "Total PV Power"
        unique_id: total_pv_power
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: "{{ (states('sensor.deye_5kw_pv_power') | float(0)) + (states('sensor.deye_6kw_pv_power') | float(0)) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_pv_power')) and is_number(states('sensor.deye_6kw_pv_power')) }}"

      - name: "Total Battery Today Discharge"
        unique_id: total_battery_today_discharge
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ (states('sensor.deye_5kw_today_battery_discharge') | float(0)) + (states('sensor.deye_6kw_today_battery_discharge') | float(0)) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_today_battery_discharge')) and is_number(states('sensor.deye_6kw_today_battery_discharge')) }}"

      - name: "Total Battery Power Realtime"
        unique_id: total_battery_power_realtime
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: "{{ (states('sensor.deye_5kw_battery_power') | float(0)) + (states('sensor.deye_6kw_battery_power') | float(0)) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_battery_power')) and is_number(states('sensor.deye_6kw_battery_power')) }}"

      - name: "Total Load Power Realtime"
        unique_id: total_load_power_realtime
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: "{{ states('sensor.deye_6kw_load_power') | float(0) }}"
        availability: "{{ is_number(states('sensor.deye_6kw_load_power')) }}"

      - name: "Total Grid Power Realtime"
        unique_id: total_grid_power_realtime
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: "{{ states('sensor.deye_5kw_grid_power') | float(0) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_grid_power')) }}"

      - name: "Total Today PV Production"
        unique_id: total_today_pv_production
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ (states('sensor.deye_5kw_today_production') | float(0)) + (states('sensor.deye_6kw_today_production') | float(0)) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_today_production')) and is_number(states('sensor.deye_6kw_today_production')) }}"

      - name: "Total Today Grid Import"
        unique_id: total_today_grid_import
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.deye_5kw_today_energy_import') | float(0) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_today_energy_import')) }}"

      - name: "Total Today Load"
        unique_id: total_today_load
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.deye_6kw_today_load_consumption') | float(0) }}"
        availability: "{{ is_number(states('sensor.deye_6kw_today_load_consumption')) }}"

      - name: "Total Today Grid Export"
        unique_id: total_today_grid_export
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.deye_5kw_today_energy_export') | float(0) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_today_energy_export')) }}"

      - name: "Total Battery Today Charge"
        unique_id: total_battery_today_charge
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ (states('sensor.deye_5kw_today_battery_charge') | float(0)) + (states('sensor.deye_6kw_today_battery_charge') | float(0)) }}"
        availability: "{{ is_number(states('sensor.deye_5kw_today_battery_charge')) and is_number(states('sensor.deye_6kw_today_battery_charge')) }}"

      - name: "Total Battery Charge Power Realtime"
        unique_id: total_battery_charge_power_realtime
        unit_of_measurement: "W"
        device_class: power
        state_class: measurement
        state: >
          {% set p5 = states('sensor.deye_5kw_battery_power') | float(0) %}
          {% set p6 = states('sensor.deye_6kw_battery_power') | float(0) %}
          {% set total = 0 %}
          {# Оскільки на графіку у вас розряд відображається коли x > 0, то заряд є від'ємним (x < 0) #}
          {% if p5 < 0 %}{% set total = total + p5 | abs %}{% endif %}
          {% if p6 < 0 %}{% set total = total + p6 | abs %}{% endif %}
          {{ total }}
        availability: "{{ is_number(states('sensor.deye_5kw_battery_power')) and is_number(states('sensor.deye_6kw_battery_power')) }}"

sensor:
  - platform: integration
    source: sensor.deye_5kw_power_losses
    name: deye_5kw_energy_losses
    unit_prefix: k
    method: trapezoidal

utility_meter:
  deye_5_losses_daily:
    source: sensor.deye_5kw_energy_losses
    cycle: daily

shell_command:
  bizon_suspend: 'ssh -p 2222 -i /ssh/id_rsa -o StrictHostKeyChecking=no yurii@192.168.1.4 "sudo systemctl suspend </dev/null >/dev/null 2>&1 &"'
  bizon_reboot: 'ssh -p 2222 -i /ssh/id_rsa -o StrictHostKeyChecking=no yurii@192.168.1.4 "sudo reboot </dev/null >/dev/null 2>&1 &"'
  bizon_poweroff: 'ssh -p 2222 -i /ssh/id_rsa -o StrictHostKeyChecking=no yurii@192.168.1.4 "sudo systemctl poweroff </dev/null >/dev/null 2>&1 &"'
  bizon_wakeup: 'wakeonlan 2c:f0:5d:7b:3e:89'

